#!/usr/bin/env python3
"""ranim.py -- animate the replayed triangle: new vertices every frame.

The GL client array was copied into the vertex buffer at GPU 0x98df2290
(x, y float pairs, clip space).  This writes N frames of a rotating
triangle to frames.bin and anim.sh, which (after rgen.py's rrun.sh has set
everything up) puts each frame's vertices in place and renders it.

Usage: ranim.py OUTDIR [N]
"""
import math, os, struct, sys

VERTS_VA = 0x98df2290
TRI = ((0.0, 0.6), (-0.6, -0.6), (0.6, -0.6))

def main():
    out = sys.argv[1]
    n = int(sys.argv[2]) if len(sys.argv) > 2 else 120
    frames = bytearray()
    for i in range(n):
        a = 2 * math.pi * i / n
        c, s = math.cos(a), math.sin(a)
        for x, y in TRI:
            frames += struct.pack('<2f', x * c - y * s, x * s + y * c)
    os.makedirs(out, exist_ok=True)
    open(os.path.join(out, 'frames.bin'), 'wb').write(frames)
    sh = """#!/bin/sh
# anim.sh [LOOPS] -- generated by ranim.py; run rrun.sh first
D=/sys/kernel/debug/apple-sgx; cd $(dirname $0)
l=0; while [ $l -lt ${1:-1} ]; do
i=0; while [ $i -lt %d ]; do
  dd if=frames.bin of=/tmp/f.bin bs=24 skip=$i count=1 2>/dev/null
  dd if=/tmp/f.bin of=$D/mem bs=16 seek=%d conv=notrunc 2>/dev/null
  echo "rkick 0x87a00000 0x87908000 0x87b00000" > $D/cmd || { echo "frame $i failed"; exit 1; }
  i=$((i+1))
done; l=$((l+1)); done
echo "$((${1:-1} * %d)) frames"; grep "r CCB" $D/regs
""" % (n, VERTS_VA // 16, n)
    open(os.path.join(out, 'anim.sh'), 'w').write(sh)
    os.chmod(os.path.join(out, 'anim.sh'), 0o755)

if __name__ == '__main__':
    main()
