#!/usr/bin/env python3
"""rsprite.py -- many textured quads ("sprites") per frame, animated, full screen.

Builds on rgen.py's tex profile (one textured draw): the draw's two vertex
attributes (state buffer +0x260: (u, v) pointer, +0x270: (x, y) pointer,
16-byte stride) are pointed at our own vertex buffer, and the draw word in
the VDM stream gets 6 indices per sprite (the captured index buffer counts
0..8191, so up to 1365 sprites).  Every frame rewrites the vertex buffer and
renders.

Usage: rsprite.py CAPDIR RTDIR OUTDIR IMAGE [N] [FRAMES]
  CAPDIR  logs/ios/tmpl/tex, RTDIR rtemu.py 768 1024 output (RT_GPU_BASE
  0x87c00000), IMAGE the sprite (any size, used as 64x64)
"""
import math, os, random, struct, subprocess, sys

W, H = 768, 1024
VB_VA = 0x9b000000
STATE_OFF = 0x98940000 - 0x9889d000      # the tex profile's state buffer in its window
DRAW_OFF = 0x30                           # the quad's draw word in the VDM stream

def quad(x, y, s):
    """Two triangles as (u, v, x, y), pixel box -> clip space."""
    nx = lambda px: px / W * 2 - 1
    ny = lambda py: py / H * 2 - 1
    x0, y0, x1, y1 = nx(x), ny(y), nx(x + s), ny(y + s)
    v = ((0, 0, x0, y0), (1, 0, x1, y0), (1, 1, x1, y1),
         (0, 0, x0, y0), (1, 1, x1, y1), (0, 1, x0, y1))
    return b''.join(struct.pack('<4f', *p) for p in v)

def main():
    cap, rtdir, out, image = sys.argv[1:5]
    n = int(sys.argv[5]) if len(sys.argv) > 5 else 150
    frames = int(sys.argv[6]) if len(sys.argv) > 6 else 300
    here = os.path.dirname(os.path.abspath(__file__))
    subprocess.check_call([sys.executable, os.path.join(here, 'rgen.py'), cap, rtdir, out,
                           '--profile', 'tex', '--fb', '0', '0', '--size', '%dx%d' % (W, H),
                           '--codebase', '0x9a060000', '--teximg', image])
    gl = bytearray(open(os.path.join(out, 'm_9889d000.bin'), 'rb').read())
    struct.pack_into('<I', gl, STATE_OFF + 0x260, VB_VA)
    struct.pack_into('<I', gl, STATE_OFF + 0x270, VB_VA + 8)
    open(os.path.join(out, 'm_9889d000.bin'), 'wb').write(gl)
    vdm = bytearray(open(os.path.join(out, 'm_98f00000.bin'), 'rb').read())
    assert struct.unpack_from('<I', vdm, DRAW_OFF)[0] == 0x81c00006
    struct.pack_into('<I', vdm, DRAW_OFF, 0x81c00000 | 6 * n)
    open(os.path.join(out, 'm_98f00000.bin'), 'wb').write(vdm)

    rnd = random.Random(1)
    sp = [[rnd.uniform(0, W - 100), rnd.uniform(0, H - 100), rnd.choice((48, 64, 96, 128)),
           rnd.uniform(-6, 6), rnd.uniform(-6, 6)] for _ in range(n)]
    fb = bytearray()
    for f in range(frames):
        for s in sp:
            s[0] += s[3]; s[1] += s[4]
            if not 0 <= s[0] <= W - s[2]: s[3] = -s[3]; s[0] = min(max(s[0], 0), W - s[2])
            if not 0 <= s[1] <= H - s[2]: s[4] = -s[4]; s[1] = min(max(s[1], 0), H - s[2])
            fb += quad(s[0], s[1], s[2])
    open(os.path.join(out, 'frames.bin'), 'wb').write(fb)
    vbsize = (n * 96 + 0xfff) & ~0xfff
    rrun = open(os.path.join(out, 'rrun.sh')).read()
    rrun = rrun.replace('echo 1 > $D/boot', 'echo "map 0x%x 0x%x" > $D/cmd 2>/dev/null\n'
                        'echo 1 > $D/boot' % (VB_VA, vbsize))
    open(os.path.join(out, 'rrun.sh'), 'w').write(rrun)
    sh = """#!/bin/sh
# anim.sh -- generated by rsprite.py: %d sprites, %d frames; run rrun.sh first
D=/sys/kernel/debug/apple-sgx; cd $(dirname $0)
i=0; while [ $i -lt %d ]; do
  dd if=frames.bin of=/tmp/f.bin bs=%d skip=$i count=1 2>/dev/null
  dd if=/tmp/f.bin of=$D/mem bs=4096 seek=%d conv=notrunc 2>/dev/null
  echo "rkick 0x87a00000 %s 0x87b00000" > $D/cmd || { echo "frame $i failed"; exit 1; }
  i=$((i+1))
done
echo "%d frames"; grep "r CCB" $D/regs
""" % (n, frames, frames, n * 96, VB_VA // 4096,
       rrun.split('rkick 0x87a00000 ')[1].split()[0], frames)
    open(os.path.join(out, 'anim.sh'), 'w').write(sh)
    os.chmod(os.path.join(out, 'anim.sh'), 0o755)

if __name__ == '__main__':
    main()
