#!/usr/bin/env bash
# Build staging-bundle.bin for iBEC Recovery ACE → Linux.
#
# Layout at 0x80000000 after irecovery -f:
#   [linux_boot loader][pad to 0x8000][zImage-dtb]
#
# Loader paints fb_text8 status (no color bars), then jumps to 0x80008000.
set -eu

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/build/out"
ZIMAGE="${1:-$OUT/zImage-dtb}"
BUNDLE="$OUT/staging-bundle.bin"
TEXT_OFF=32768

CC=arm-linux-gnueabihf-gcc
OBJCOPY=arm-linux-gnueabihf-objcopy

# Default input is zImage-dtb. If a fresher plain zImage exists, refuse to
# silently wrap yesterday's DTB append (that shipped old color-band kernels).
if [ "${1:-}" = "" ] && [ -f "$OUT/zImage" ] && [ -f "$ZIMAGE" ]; then
	if [ "$OUT/zImage" -nt "$ZIMAGE" ]; then
		echo "error: $OUT/zImage is newer than $ZIMAGE" >&2
		echo "  rebuild the append first, e.g.:" >&2
		echo "    bash scripts/append-dtb.sh build/out/zImage dtb/p105ap.dtb build/out/zImage-dtb" >&2
		exit 1
	fi
fi

[ -f "$ZIMAGE" ] || { echo "missing zImage-dtb: $ZIMAGE" >&2; exit 1; }

# zImage is compressed — stamp strings live in vmlinux from the last build.
VMLINUX="$ROOT/build/linux/vmlinux"
echo "==> Verifying kernel stamps in $VMLINUX"
[ -f "$VMLINUX" ] || { echo "error: missing $VMLINUX — run: bash scripts/build-kernel.sh" >&2; exit 1; }
if [ "$VMLINUX" -nt "$OUT/zImage" ]; then
	echo "error: vmlinux newer than $OUT/zImage — finish build-kernel.sh first" >&2
	exit 1
fi
if grep -aFq 'rest_clone' "$VMLINUX"; then
    echo "error: vmlinux contains rest_clone — run: bash scripts/build-kernel.sh" >&2
    exit 1
fi
for need in pre_spawn umt_go aic1q34 irq_try; do
    if ! grep -aFq "$need" "$VMLINUX"; then
        echo "error: vmlinux missing '$need' — rebuild kernel first" >&2
        exit 1
    fi
done
echo "  ok: fresh P105 boot stamps (pre_spawn umt_go aic1q34 irq_try)"

ksz=$(stat -c%s "$ZIMAGE")
mkdir -p "$OUT"

python3 - "$ZIMAGE" "$ROOT/pongo/staging-generated.h" <<'PY'
import struct, sys
from pathlib import Path
z, inc = Path(sys.argv[1]), Path(sys.argv[2])
d = z.read_bytes()
off = d.rfind(bytes.fromhex("d00dfeed"))
if off < 0:
    raise SystemExit("zImage-dtb has no DTB magic")
tot = struct.unpack_from(">I", d, off + 4)[0]
va = 0x80008000 + off
inc.write_text(
    f"/* Auto-generated by build-staging-bundle.sh — do not edit */\n"
    f"#ifndef STAGING_GENERATED_H\n#define STAGING_GENERATED_H\n"
    f"#define DTB_PHYS {va:#x}u\n"
    f"#define DTB_SIZE {tot:#x}u\n"
    f"#endif\n"
)
print(f"  DTB_PHYS {va:#x}  DTB_SIZE {tot:#x}  (file off {off:#x})")
PY

# Keep asm-era .inc in sync for any leftover consumers
python3 - "$ZIMAGE" "$ROOT/pongo/staging-generated.inc" <<'PY'
import struct, sys
from pathlib import Path
z, inc = Path(sys.argv[1]), Path(sys.argv[2])
d = z.read_bytes()
off = d.rfind(bytes.fromhex("d00dfeed"))
tot = struct.unpack_from(">I", d, off + 4)[0]
va = 0x80008000 + off
inc.write_text(f"\t.equ\tDTB_PHYS, {va:#x}\n\t.equ\tDTB_SIZE, {tot:#x}\n")
PY

"$CC" -static -nostdlib -nostartfiles -O2 \
    -I "$ROOT/pongo" \
    -fno-builtin -ffreestanding \
    -Wl,--no-warn-rwx-segments -Wl,--build-id=none \
    -Wl,-T,"$ROOT/pongo/linux-boot.ld" \
    -o "$OUT/linux-boot.elf" \
    "$ROOT/pongo/linux_boot_start.S" \
    "$ROOT/pongo/linux_boot.c"

"$OBJCOPY" -O binary "$OUT/linux-boot.elf" "$OUT/linux-boot.bin"
# Compat name used by flashdrive boot scripts
cp -f "$OUT/linux-boot.bin" "$OUT/staging-loader.bin"

cp "$OUT/linux-boot.bin" "$BUNDLE"
cp "$OUT/linux-boot.bin" "$ROOT/flashdrive/staging-loader.bin"
cp "$OUT/linux-boot.bin" "$ROOT/flashdrive/linux-boot.bin"
lsz=$(stat -c%s "$BUNDLE")
if [ "$lsz" -gt "$TEXT_OFF" ]; then
    echo "linux-boot.bin is ${lsz} bytes (max ${TEXT_OFF})" >&2
    exit 1
fi
pad=$((TEXT_OFF - lsz))
if [ "$pad" -gt 0 ]; then
    dd if=/dev/zero bs=1 count="$pad" status=none >> "$BUNDLE"
fi
cat "$ZIMAGE" >> "$BUNDLE"
cp -f "$BUNDLE" "$ROOT/flashdrive/staging-bundle.bin"

echo "built $BUNDLE"
echo "  loader : ${lsz} bytes + ${pad} pad  (fb_text8, no color bars)"
echo "  kernel : ${ksz} bytes"
echo "  total  : $(stat -c%s "$BUNDLE") bytes"
echo "  upload : irecovery -f staging-bundle.bin  (0x80000000)"
echo "  jump   : ACE autogo → loader → 0x80008000"
