# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_ARCH_APPLE_S5L)	+= apple.o pmccntr.o p105_fb_dbg.o apple_wdt_clkevt.o apple_pmu_clkevt.o apple_sof_clkevt.o
obj-$(CONFIG_SMP)		+= platsmp.o headsmp.o
